src/Web/Models/HomeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Web.Models
{
    public class HomeViewModel
    {
        public List<ProductViewModel> Products { get; set; } = new();

        public List<SelectListItem> Categories { get; set; } = new();

        public List<SelectListItem> Brands { get; set; } = new();

        public int? CategoryId { get; set; }

        public int? BrandId { get; set; }

        public PaginationInfoViewModel PaginationInfo { get; set; } = null!;
    }
}

src/Web/Controllers/BasketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Interfaces;
using Web.Models;

namespace Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketViewModelService _basketViewModelService;

        public BasketController(IBasketViewModelService basketViewModelService)
        {
            _basketViewModelService = basketViewModelService;
        }

        public async Task<IActionResult> Index()
        {
            var vm = await _basketViewModelService.GetBasketViewModelAsync();
            return View(vm);
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            var vm = new CheckoutViewModel()
            {
                Basket = await _basketViewModelService.GetBasketViewModelAsync()
            };
            return View(vm);
        }


        [Authorize, HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutViewModel vm)
        {
            if (ModelState.IsValid)
            {
                // payment
                // ...

                await _basketViewModelService.CheckoutAsync(vm.Street, vm.City, vm.State, vm.Country, vm.ZipCode);

                return RedirectToAction("OrderConfirmed");
            }

            vm.Basket = await _basketViewModelService.GetBasketViewModelAsync();
            return View(vm);
        }

        [Authorize]
        public async Task<IActionResult> OrderConfirmed()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddToBasket(int productId)
        {
            var vm = await _basketViewModelService.AddItemToBasketAsync(productId, 1);
            return Json(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Empty()
        {
            await _basketViewModelService.EmptyBasketAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int productId)
        {
            await _basketViewModelService.DeleteBasketItemAsync(productId);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([ModelBinder(Name = "quantities")] Dictionary<int, int> quantities)
        {
            await _basketViewModelService.UpdateBasketAsync(quantities);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Web.Interfaces;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeViewModelService _homeViewModelService;

        public HomeController(IHomeViewModelService homeViewModelService)
        {
            _homeViewModelService = homeViewModelService;
        }

        public async Task<IActionResult> Index(int? categoryId, int? brandId, int pageId = 1)
        {
            var vm = await _homeViewModelService.GetHomeViewModelAsync(categoryId, brandId, pageId);
            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<form class="d-flex align-items-center border rounded p-2 mt-2 mb-4 bg-light" method="get">
    <label asp-for="CategoryId" class="me-2">Category</label>
    <select asp-for="CategoryId" asp-items="Model.Categories" class="form-select me-3 w-auto">
        <option value="">Choose..</option>
    </select>
    <label asp-for="BrandId" class="me-2">Brand</label>
    <select asp-for="BrandId" asp-items="Model.Brands" class="form-select me-3 w-auto">
        <option value="">Choose..</option>
    </select>
    <button class="btn btn-primary">Submit</button>
</form>

<div class="row">
    @foreach (var item in Model.Products)
    {
        <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="product shadow-sm p-3 mb-5">
                <img class="product-image w-100" src="~/img/products/@item.PictureUri" alt="Product" />
                <div class="product-name mb-2">
                    @item.Name
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="product-price fw-bold">@item.Price.ToString("c2")</div>
                    <button data-add-to-basket="@item.Id" class="product-add btn btn-sm btn-outline-success">
                        <i class="fa-solid fa-cart-plus"></i>
                    </button>
                </div>
            </div>
        </div>
    }
</div>

@{ var pi = Model.PaginationInfo; }
<nav>
    <ul class="pagination justify-content-center">
        @if (pi.HasPrevious)
        {
            <li class="page-item">
                <a class="page-link" asp-route-pageId="@(pi.PageId - 1)" asp-route-categoryId="@Model.CategoryId" asp-route-brandId="@Model.BrandId">
                    <span>&laquo;</span>
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link">
                    <span>&laquo;</span>
                </a>
            </li>
        }

        @foreach (var i in pi.PageNumbers)
        {
            if (i == -1)
            {
                <li class="page-item disabled">
                    <a class="page-link">
                        <span>&hellip;</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item @(i == pi.PageId ? "active" : "")">
                    <a class="page-link" asp-route-pageId="@i" asp-route-categoryId="@Model.CategoryId" asp-route-brandId="@Model.BrandId">@i</a>
                </li>
            }
        }

        @if (pi.HasNext)
        {
            <li class="page-item">
                <a class="page-link" asp-route-pageId="@(pi.PageId + 1)" asp-route-categoryId="@Model.CategoryId" asp-route-brandId="@Model.BrandId">
                    <span>&raquo;</span>
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link">
                    <span>&raquo;</span>
                </a>
            </li>
        }
    </ul>
</nav>
<div class="text-center">
    Showing @pi.RangeStart-@pi.RangeEnd of @pi.TotalItems 
</div>

@section Scripts {
    <script>
        $("[data-add-to-basket]").click(function () {
            let productId = $(this).data("add-to-basket");
            let url = "@Url.Action("AddToBasket", "Basket")";
            $.post(url, { productId }, function (data) {
                $("[data-total-items]").text(data.totalItems);
            });
        });
    </script>
}